# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0004_auto_20180307_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('2', 'Accounting Manager'), ('1', 'Product Manager'), ('3', 'Regular User'), ('0', 'Administrator')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_thumbnail',
            field=models.ImageField(blank=True, default='productPhoto/AnonymousUser.png', null=True, upload_to='productPhoto/'),
        ),
    ]
