# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0008_auto_20180307_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('2', 'Smart Watch'), ('0', 'Analog Watch'), ('1', 'Digital Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('0', 'Administrator'), ('3', 'Regular User'), ('2', 'Accounting Manager'), ('1', 'Product Manager')], default='3', max_length=16),
        ),
    ]
