# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0011_auto_20180307_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_email',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='productPhoto/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('0', 'Analog Watch'), ('1', 'Digital Watch'), ('2', 'Smart Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('0', 'Administrator'), ('3', 'Regular User'), ('2', 'Accounting Manager'), ('1', 'Product Manager')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_thumbnail',
            field=models.ImageField(blank=True, default='productPhoto/AnonymousUser.png', null=True, upload_to='productPhoto/'),
        ),
    ]
