# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0012_auto_20180307_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Digital Watch'), ('2', 'Smart Watch'), ('0', 'Analog Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('1', 'Product Manager'), ('2', 'Accounting Manager'), ('3', 'Regular User'), ('0', 'Administrator')], default='3', max_length=16),
        ),
    ]
