# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0015_auto_20180307_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('3', 'Regular User'), ('1', 'Product Manager'), ('2', 'Accounting Manager'), ('0', 'Administrator')], default='3', max_length=16),
        ),
    ]
