# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0018_auto_20180308_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('1', 'Product Manager'), ('0', 'Administrator'), ('2', 'Accounting Manager'), ('3', 'Regular User')], default='3', max_length=16),
        ),
    ]
