# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0022_auto_20180312_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='product_quantity',
            new_name='transaction_quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product_order_total',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='trasaction_order_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('4', '4 Star'), ('1', '1 Star'), ('5', '5 Star'), ('2', '2 Star'), ('3', '3 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Digital Watch'), ('2', 'Smart Watch'), ('0', 'Analog Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('3', 'Regular User'), ('1', 'Product Manager'), ('0', 'Administrator'), ('2', 'Accounting Manager')], default='3', max_length=16),
        ),
    ]
