# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0024_auto_20180312_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trasaction_order_total',
            new_name='transaction_order_total',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('1', '1 Star'), ('3', '3 Star'), ('4', '4 Star'), ('2', '2 Star'), ('5', '5 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('0', 'Analog Watch'), ('2', 'Smart Watch'), ('1', 'Digital Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('2', 'Accounting Manager'), ('0', 'Administrator'), ('3', 'Regular User'), ('1', 'Product Manager')], default='3', max_length=16),
        ),
    ]
