# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0027_auto_20180312_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('1', '1 Star'), ('5', '5 Star'), ('3', '3 Star'), ('4', '4 Star'), ('2', '2 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 12, 45, 28, 322723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('2', 'Accounting Manager'), ('0', 'Administrator'), ('1', 'Product Manager'), ('3', 'Regular User')], default='3', max_length=16),
        ),
    ]
