# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0031_auto_20180313_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('0', 'Administrator'), ('1', 'Product Manager'), ('3', 'Regular User'), ('2', 'Accounting Manager')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('2', '2 Star'), ('3', '3 Star'), ('1', '1 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Digital Watch'), ('2', 'Smart Watch'), ('0', 'Analog Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('0', 'Administrator'), ('1', 'Product Manager'), ('3', 'Regular User'), ('2', 'Accounting Manager')], default='3', max_length=16),
        ),
    ]
