# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0033_auto_20180313_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_total', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('3', '3 Star'), ('1', '1 Star'), ('2', '2 Star'), ('5', '5 Star'), ('4', '4 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('2', 'Smart Watch'), ('1', 'Digital Watch'), ('0', 'Analog Watch')], default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='transactionextension',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aion.Product'),
        ),
    ]
