# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 06:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0035_auto_20180313_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('2', '2 Star'), ('4', '4 Star'), ('3', '3 Star'), ('5', '5 Star'), ('1', '1 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Digital Watch'), ('0', 'Analog Watch'), ('2', 'Smart Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Invalid Email!')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('0', 'Administrator'), ('2', 'Accounting Manager'), ('3', 'Regular User'), ('1', 'Product Manager')], default='3', max_length=16),
        ),
    ]
