# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 06:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0036_auto_20180415_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('3', '3 Star'), ('1', '1 Star'), ('5', '5 Star'), ('4', '4 Star'), ('2', '2 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('2', 'Smart Watch'), ('0', 'Analog Watch'), ('1', 'Digital Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Invalid Email!')]),
        ),
    ]
