# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0039_auto_20180415_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('1', '1 Star'), ('3', '3 Star'), ('2', '2 Star'), ('5', '5 Star'), ('4', '4 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('2', 'Smart Watch'), ('1', 'Digital Watch'), ('0', 'Analog Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('2', 'Accounting Manager'), ('3', 'Regular User'), ('0', 'Administrator'), ('1', 'Product Manager')], default='3', max_length=16),
        ),
    ]
