# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0040_auto_20180415_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Digital Watch'), ('0', 'Analog Watch'), ('2', 'Smart Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('1', 'Product Manager'), ('0', 'Administrator'), ('2', 'Accounting Manager'), ('3', 'Regular User')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='billing_house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='billing_postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='shipping_house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='shipping_postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
