# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 08:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0041_auto_20180415_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('3', '3 Star'), ('4', '4 Star'), ('1', '1 Star'), ('5', '5 Star'), ('2', '2 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('0', 'Analog Watch'), ('2', 'Smart Watch'), ('1', 'Digital Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Invalid Email!')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('1', 'Product Manager'), ('2', 'Accounting Manager'), ('3', 'Regular User'), ('0', 'Administrator')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='billing_house_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='shipping_house_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
