# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0043_auto_20180415_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('2', '2 Star'), ('1', '1 Star'), ('4', '4 Star'), ('3', '3 Star'), ('5', '5 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('0', 'Administrator'), ('1', 'Product Manager'), ('3', 'Regular User'), ('2', 'Accounting Manager')], default='3', max_length=16),
        ),
    ]
