# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aion', '0049_auto_20180420_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_thumbnail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_thumbnail',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.CharField(choices=[('2', '2 Star'), ('5', '5 Star'), ('1', '1 Star'), ('4', '4 Star'), ('3', '3 Star')], default='3', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('1', 'Digital Watch'), ('2', 'Smart Watch'), ('0', 'Analog Watch')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.CharField(choices=[('1', 'Product Manager'), ('3', 'Regular User'), ('0', 'Administrator'), ('2', 'Accounting Manager')], default='3', max_length=16),
        ),
    ]
